CREATE TABLE CARE_TAKER (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(255) NOT NULL,
    relation VARCHAR(255) NOT NULL,
    type VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    note VARCHAR(255) NOT NULL
);